version: '3.2'
services:
  brandr-app:
    container_name: brandr-app
    image: scienta/brandr-app:branch-master
    restart: always
    ports:
      - "${BIND_INTERFACE}:8080:80"
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
    command: /bin/sh -c "envsubst '$${API_ENDPOINT}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
